name = "aichat-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "aichat-db"
database_id = "403e4419-a4f3-4106-82ab-b3404f3598dc"

[ai]
binding = "AI"

[vars]
SITE_NAME = "AI Chat Pro"

